export const todosConstants = {
  ADD_RECORD_REQUEST: "ADD_RECORD_REQUEST",
  ADD_RECORD_SUCCESS: "ADD_RECORD_SUCCESS",
  ADD_RECORD_FAILURE: "ADD_RECORD_FAILURE",

  DELETE_RECORD_REQUEST: "DELETE_RECORD_REQUEST",
  DELETE_RECORD_SUCCESS: "DELETE_RECORD_SUCCESS",
  DELETE_RECORD_FAILURE: "DELETE_RECORD_FAILURE",

  EDIT_RECORD_REQUEST: "EDIT_RECORD_REQUEST",
  EDIT_RECORD_SUCCESS: "EDIT_RECORD_SUCCESS",
  EDIT_RECORD_FAILURE: "EDIT_RECORD_FAILURE",

  GET_RECORD_REQUESTS: "GET_RECORD_REQUESTS",
  GET_RECORD_SUCCESS: "GET_RECORD_SUCCESS",
  GET_RECORD_FAILURE: "GET_RECORD_FAILURE",
};
export const authConstant = {
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",

  SIGNUP_AUTH_REQUEST: "SIGNUP_AUTH_REQUEST",
  SIGNUP_AUTH_SUCCESS: "SIGNUP_AUTH_SUCCESS",
  SIGNUP_AUTH_FAILURE: "SIGNUP_AUTH_FAILURE",

  REGISTER_AUTH_REQUEST: "REGISTER_AUTH_REQUEST",
  REGISTER_AUTH_SUCCESS: "REGISTER_AUTH_SUCCESS",
  REGISTER_AUTH_FAILURE: "REGISTER_AUTH_FAILURE",

  LOGOUT_AUTH_REQUEST: "LOGOUT_AUTH_REQUEST",
  LOGOUT_AUTH_SUCCESS: "LOGOUT_AUTH_SUCCESS",
  LOGOUT_AUTH_FAILURE: "LOGOUT_AUTH_FAILURE",
};
export const cartConstant = {
  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",

  DELETE_CART_REQUEST: "DELETE_CART_REQUEST",
  DELETE_CART_SUCCESS: "DELETE_CART_SUCCESS",
  DELETE_CART_FAILURE: "DELETE_CART_FAILURE",

  ADD_TO_CART_REQUEST: "ADD_TO_CART_AUTH_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_AUTH_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_AUTH_FAILURE",
};
